// Generated by gencpp from file pixhawk/imu_gps.msg
// DO NOT EDIT!


#ifndef PIXHAWK_MESSAGE_IMU_GPS_H
#define PIXHAWK_MESSAGE_IMU_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pixhawk
{
template <class ContainerAllocator>
struct imu_gps_
{
  typedef imu_gps_<ContainerAllocator> Type;

  imu_gps_()
    : header()
    , latitude(0.0)
    , lontitude(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , angle(0.0)  {
    }
  imu_gps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , lontitude(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _lontitude_type;
  _lontitude_type lontitude;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vz_type;
  _vz_type vz;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::pixhawk::imu_gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pixhawk::imu_gps_<ContainerAllocator> const> ConstPtr;

}; // struct imu_gps_

typedef ::pixhawk::imu_gps_<std::allocator<void> > imu_gps;

typedef boost::shared_ptr< ::pixhawk::imu_gps > imu_gpsPtr;
typedef boost::shared_ptr< ::pixhawk::imu_gps const> imu_gpsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pixhawk::imu_gps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pixhawk::imu_gps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pixhawk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pixhawk': ['/home/sailing/catkin_wws/src/pixhawk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pixhawk::imu_gps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pixhawk::imu_gps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhawk::imu_gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pixhawk::imu_gps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhawk::imu_gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pixhawk::imu_gps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pixhawk::imu_gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70a91dc3b9e5b19727d01ebd6e65eb98";
  }

  static const char* value(const ::pixhawk::imu_gps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70a91dc3b9e5b197ULL;
  static const uint64_t static_value2 = 0x27d01ebd6e65eb98ULL;
};

template<class ContainerAllocator>
struct DataType< ::pixhawk::imu_gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixhawk/imu_gps";
  }

  static const char* value(const ::pixhawk::imu_gps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pixhawk::imu_gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 latitude\n\
float32 lontitude\n\
float32 vx\n\
float32 vy\n\
float32 vz\n\
float32 angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pixhawk::imu_gps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pixhawk::imu_gps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.lontitude);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_gps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pixhawk::imu_gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pixhawk::imu_gps_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "lontitude: ";
    Printer<float>::stream(s, indent + "  ", v.lontitude);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIXHAWK_MESSAGE_IMU_GPS_H
